#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-Cython
Version  : 0.29.6
Release  : 76
URL      : https://files.pythonhosted.org/packages/36/da/fcb979fc8cb486a67a013d6aefefbb95a3e19e67e49dff8a35e014046c5e/Cython-0.29.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/36/da/fcb979fc8cb486a67a013d6aefefbb95a3e19e67e49dff8a35e014046c5e/Cython-0.29.6.tar.gz
Summary  : The Cython compiler for writing C extensions for the Python language.
Group    : Development/Tools
License  : Apache-2.0 Python-2.0
Requires: deprecated-Cython-bin = %{version}-%{release}
Requires: deprecated-Cython-license = %{version}-%{release}
Requires: deprecated-Cython-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : coverage
BuildRequires : gdb
BuildRequires : ipython
BuildRequires : numpy
BuildRequires : python-core
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools-legacypython

%description
Welcome to Cython's documentation.
To build the documentation on Linux, you need Make and Sphinx installed on your system. Then execute::

%package bin
Summary: bin components for the deprecated-Cython package.
Group: Binaries
Requires: deprecated-Cython-license = %{version}-%{release}

%description bin
bin components for the deprecated-Cython package.


%package legacypython
Summary: legacypython components for the deprecated-Cython package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-Cython package.


%package license
Summary: license components for the deprecated-Cython package.
Group: Default

%description license
license components for the deprecated-Cython package.


%package python
Summary: python components for the deprecated-Cython package.
Group: Default
Provides: deprecated-cython-python

%description python
python components for the deprecated-Cython package.


%prep
%setup -q -n Cython-0.29.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554311051
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-Cython
cp COPYING.txt %{buildroot}/usr/share/package-licenses/deprecated-Cython/COPYING.txt
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-Cython/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/cygdb
%exclude /usr/bin/cython
%exclude /usr/bin/cythonize

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-Cython/COPYING.txt
/usr/share/package-licenses/deprecated-Cython/LICENSE.txt

%files python
%defattr(-,root,root,-)
